#! /bin/bash

export VERSION="46"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="12000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-neroreflex"
export KERNEL_PACKAGE_ORIGIN="local"

#removed packages:
# broadcom-wl-dkms \
export PACKAGES="\
	cmake \
	clang \
	llvm \
	lld \
	flex \
	bison \
	bc \
	m4 \
	accountsservice \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bash-completion \
	bzip2 \
	cifs-utils \
	cpupower \
	diffutils \
	dkms \
	distrobox \
	dmidecode \
	dosbox \
	dolphin \
	efibootmgr \
	epiphany \
	evtest \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	git \
	gst-plugin-pipewire \
	gzip \
	haveged \
	htop \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	iio-sensor-proxy \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-vdpau-driver \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	loupe \
	lshw \
	modemmanager \
	nano \
	networkmanager \
	nfs-utils \
	noto-fonts-emoji \
	nss-mdns \
	openal \
	openrazer-daemon \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-pulse \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	tar \
	tree \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	vulkan-tools \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-zenhei \
	xdg-desktop-portal \
	xdg-desktop-portal-kde \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	xz \
	zip \
	plasma \
	plasma-desktop \
	kate \
	kcalc \
	kwin \
	konsole \
	yakuake \
	sddm \
	ark \
	kdeconnect \
	kdenetwork-filesharing \
	dolphin-plugins \
	qjackctl \
	jack2 \
	lib32-jack2 \
	jack2-dbus \
	libffado \
	pipewire-jack-client \
	realtime \
	qtractor \
	zsh \
"

export PACKAGE_OVERRIDES="\
	https://github.com/rog-ally-gaming/linux-chimeraos/releases/download/6.1.81.nrflx3-2/linux-neroreflex-6.1.81.nrflx3-2-x86_64.pkg.tar.zst \
	https://github.com/rog-ally-gaming/linux-chimeraos/releases/download/6.1.81.nrflx3-2/linux-neroreflex-api-headers-6.1.81.nrflx3-2-x86_64.pkg.tar.zst \
	https://github.com/rog-ally-gaming/linux-chimeraos/releases/download/6.1.81.nrflx3-2/linux-neroreflex-headers-6.1.81.nrflx3-2-x86_64.pkg.tar.zst \
	https://github.com/rog-ally-gaming/asusctl/releases/download/5.0.7-1/asusctl-5.0.7-1-x86_64.pkg.tar.zst \
	https://github.com/rog-ally-gaming/asusctl/releases/download/5.0.7-1/rog-control-center-5.0.7-1-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/repos/2023/06/28/extra/os/x86_64/libretro-pcsx2-11900-2-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/l/libretro-mame/libretro-mame-85763-1-x86_64.pkg.tar.zst \
"


# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
#removed packages:
#   r8152-dkms \
#	r8168-dkms \
#	rtl8812au-dkms-git \
#	rtl8814au-dkms-git \
#	rtl88x2bu-dkms-git \
#	rtl8821au-dkms-git \
#	rtw89-dkms-git \
#
export AUR_PACKAGES="\
	brscan4 \
	brother-dcp-l2510d \
	bcm20702a1-firmware \
	boxtron \
	chimera \
	chimeraos-device-quirks-git \
	downgrade \
	exa \
	gamescope-session-steam-git \
	gamescope-session-steam-plus-git \
	hhfc-git \
	legendary \
	lib32-gamescope-plus \
	lib32-gperftools \
	libretro-dosbox-pure-git \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	nintendo-udev \
	pikaur \
	powerstation-bin \
	polychromatic \
	python-vdf \
	retroarch-autoconfig-udev-git \
	ryzenadj-git \
	steam_notif_daemon \
	steam-removable-media-git \
	wyvern \
	zenergy-dkms-git \
	matchbox-keyboard \
	rtcqs \
	zsh-theme-powerlevel10k-git \
	ttf-meslo-nerd-font-powerlevel10k \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	cups \
	fstrim.timer \
	rogue-enemy \
	haveged \
	home-swapfile.swap \
	powerstation \
	sshd \
	systemd-timesyncd \
	systemd-sysext \
	sddm \
"

export USER_SERVICES="\
	chimera.service \
	pipewire \
	steam-patch.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/libretro/autoconfig/udev/Gasia_PS_Gamepad_USB.cfg \
	/usr/share/libretro/autoconfig/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg \
	/usr/share/libretro/autoconfig/udev/Xbox_360_Wireless_Receiver_Chinese01.cfg \
"

postinstallhook() {
	# chimeraos requires ladspa-host and the default provider is ardour
	# qtractor is installed to spare space so it's safe to remove ardour
	# pacman -R --noconfirm ardour # turns out ardour doesn't get installed when qtractor is being specified

	## now all orphan dependencies must be removed (to spare space)
	#pacman -Qqd | pacman -Rsu - 

	# Remove discover software
	pacman -Rs --noconfirm discover
	
	#yes|pacman -Scc
	ls -lah /var/cache/pacman

	mkdir -p /etc/sddm.conf.d
	echo "[General]" > /etc/sddm.conf.d/steam-deckify.conf
	echo "DisplayServer=wayland" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "[Autologin]" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "Relogin=true" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "Session=steamos.desktop" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "User=${USERNAME}" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "[X11]" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "# Janky workaround for wayland sessions not stopping in sddm, kills" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "# all active sddm-helper sessions on teardown" >> /etc/sddm.conf.d/steam-deckify.conf
	echo "DisplayStopCommand=/usr/bin/gamescope-wayland-teardown-workaround" >> /etc/sddm.conf.d/steam-deckify.conf

	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" > /etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" > /etc/sudoers.d/chimera

	# Add chrt permission
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chrt" > /etc/sudoers.d/realtime

	# disable retroarch menu in joypad configs
	find /usr/share/libretro/autoconfig -type f -name '*.cfg' | xargs -d '\n' sed -i '/input_menu_toggle_btn/d'

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	#rm /usr/share/libalpm/hooks/70-dkms-install.hook
	#rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	#rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	#pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	# dolphin-tool is no longer created in new builds?
	#rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

	# set permissions for intel_gpu_top and mangohud
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top

	# remove r8169 blacklist in /usr, leave it up to the user
	rm -rf /usr/lib/modprobe.d/r8168-dkms.conf

	# files in /etc/extensions will be auto-mounted by systemd-sysext
	mkdir /etc/extensions

	echo "" >> /etc/environment
	echo "SDL_GAMECONTROLLER_IGNORE_DEVICES=\"0x045E/0x028E\"" >> /etc/environment
	echo "" >> /etc/environment
	echo "# This makes a few games (like Ori and the blind forest) crash as startup for not being able to create the rendering surface" >> /etc/environment
	echo "#ENABLE_GAMESCOPE_WSI=1" >> /etc/environment
}
